In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

In [ ]:
# 데이터 정의
data_1 = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
data_2 = torch.tensor([2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0])
data = [data_1, data_2]

In [1]:
# 오토인코더 모델 정의
class Autoencoder(nn.Module):
    def __init__(self):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(8, 4),
            nn.ReLU(),
            nn.Linear(4, 2),
            nn.ReLU()
        )
        self.decoder = nn.Sequential(
            nn.Linear(2, 4),
            nn.ReLU(),
            nn.Linear(4, 8)
        )

    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x

In [2]:
# 모델 초기화 및 옵티마이저, 손실 함수 설정
model = Autoencoder()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [7]:
# 훈련
epochs = 10000
for epoch in tqdm(range(epochs), desc="Training"):
    total_loss = 0
    for d in data:
        optimizer.zero_grad()
        outputs = model(d)
        loss = criterion(outputs, d)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    if (epoch+1) % 1000 == 0:  # 1000 에포크마다 평균 로스 출력
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {total_loss/len(data):.4f}")

Training:  10%|█         | 1046/10000 [00:03<00:37, 238.77it/s]

Epoch [1000/10000], Loss: 0.0000


Training:  21%|██        | 2072/10000 [00:06<00:20, 395.29it/s]

Epoch [2000/10000], Loss: 0.0000


Training:  30%|███       | 3040/10000 [00:09<00:18, 383.80it/s]

Epoch [3000/10000], Loss: 0.0000


Training:  41%|████      | 4065/10000 [00:12<00:15, 395.59it/s]

Epoch [4000/10000], Loss: 0.0000


Training:  51%|█████     | 5074/10000 [00:14<00:13, 373.77it/s]

Epoch [5000/10000], Loss: 0.0000


Training:  60%|██████    | 6045/10000 [00:17<00:10, 373.28it/s]

Epoch [6000/10000], Loss: 0.0000


Training:  71%|███████   | 7069/10000 [00:20<00:07, 392.31it/s]

Epoch [7000/10000], Loss: 0.0000


Training:  81%|████████  | 8059/10000 [00:23<00:05, 338.09it/s]

Epoch [8000/10000], Loss: 0.0000


Training:  91%|█████████ | 9067/10000 [00:25<00:02, 396.96it/s]

Epoch [9000/10000], Loss: 0.0000


Training: 100%|██████████| 10000/10000 [00:28<00:00, 353.13it/s]

Epoch [10000/10000], Loss: 0.0000


In [8]:
# 결과 테스트
with torch.no_grad():
    output_1 = model(data_1)
    output_2 = model(data_2)
    print(output_1)
    print(output_2)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2., 2., 2., 2.])


In [9]:
# 2차원으로 축소된 값을 출력
with torch.no_grad():
    encoded_1 = model.encoder(data_1)
    encoded_2 = model.encoder(data_2)
    print("Encoded data_1:", encoded_1)
    print("Encoded data_2:", encoded_2)


Encoded data_1: tensor([0.0000, 2.3523])
Encoded data_2: tensor([0.0000, 5.3023])


In [21]:
model(torch.tensor([3, 3, 3, 3, 3, 3, 3, 3]))

RuntimeError: ignored

In [22]:
model(torch.tensor([3, 3, 3, 3, 3, 3, 3, 3], dtype=torch.float))

tensor([3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012],
       grad_fn=<ViewBackward0>)

In [23]:
for i in range(10):
    print(i)
    print(model(torch.tensor([i]*8, dtype=torch.float)))

0
tensor([0.2223, 0.2650, 0.4488, 0.0590, 0.1220, 0.0874, 0.4009, 0.0870],
       grad_fn=<ViewBackward0>)
1
tensor([1., 1., 1., 1., 1., 1., 1., 1.], grad_fn=<ViewBackward0>)
2
tensor([2., 2., 2., 2., 2., 2., 2., 2.], grad_fn=<ViewBackward0>)
3
tensor([3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012],
       grad_fn=<ViewBackward0>)
4
tensor([4.0081, 4.0081, 4.0081, 4.0081, 4.0081, 4.0081, 4.0081, 4.0081],
       grad_fn=<ViewBackward0>)
5
tensor([5.0149, 5.0149, 5.0149, 5.0149, 5.0149, 5.0149, 5.0149, 5.0149],
       grad_fn=<ViewBackward0>)
6
tensor([6.0217, 6.0217, 6.0217, 6.0217, 6.0217, 6.0217, 6.0217, 6.0218],
       grad_fn=<ViewBackward0>)
7
tensor([7.0286, 7.0286, 7.0286, 7.0286, 7.0286, 7.0286, 7.0286, 7.0286],
       grad_fn=<ViewBackward0>)
8
tensor([8.0354, 8.0354, 8.0354, 8.0354, 8.0354, 8.0354, 8.0354, 8.0354],
       grad_fn=<ViewBackward0>)
9
tensor([9.0423, 9.0423, 9.0423, 9.0423, 9.0423, 9.0423, 9.0423, 9.0423],
       grad_fn=<ViewBackward0>)


In [31]:
model(torch.tensor([15]*8, dtype=torch.float))

tensor([15.0833, 15.0833, 15.0833, 15.0833, 15.0833, 15.0833, 15.0833, 15.0833],
       grad_fn=<ViewBackward0>)

In [32]:
model(torch.tensor([105]*8, dtype=torch.float))

tensor([106.0827, 106.1719, 105.9778, 106.1272, 106.2469, 106.2655, 105.9706,
        106.0258], grad_fn=<ViewBackward0>)

In [33]:
model(torch.tensor([1000]*8, dtype=torch.float))

tensor([1011.8774, 1013.0519, 1010.4957, 1012.4641, 1014.0402, 1014.2852,
        1010.4008, 1011.1271], grad_fn=<ViewBackward0>)

각 숫자의 예측 시에 Latent Vector를 출력해 보죠

In [34]:
for i in range(10):
    print(i)
    input_vector = torch.tensor([i]*8, dtype=torch.float)
    print(model.encoder(input_vector))
    print(model(input_vector))

0
tensor([0., 0.], grad_fn=<ReluBackward0>)
tensor([0.2223, 0.2650, 0.4488, 0.0590, 0.1220, 0.0874, 0.4009, 0.0870],
       grad_fn=<ViewBackward0>)
1
tensor([0.0000, 2.3523], grad_fn=<ReluBackward0>)
tensor([1., 1., 1., 1., 1., 1., 1., 1.], grad_fn=<ViewBackward0>)
2
tensor([0.0000, 5.3023], grad_fn=<ReluBackward0>)
tensor([2., 2., 2., 2., 2., 2., 2., 2.], grad_fn=<ViewBackward0>)
3
tensor([0.0000, 8.2560], grad_fn=<ReluBackward0>)
tensor([3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012, 3.0012],
       grad_fn=<ViewBackward0>)
4
tensor([ 0.0000, 11.2262], grad_fn=<ReluBackward0>)
tensor([4.0081, 4.0081, 4.0081, 4.0081, 4.0081, 4.0081, 4.0081, 4.0081],
       grad_fn=<ViewBackward0>)
5
tensor([ 0.0000, 14.1963], grad_fn=<ReluBackward0>)
tensor([5.0149, 5.0149, 5.0149, 5.0149, 5.0149, 5.0149, 5.0149, 5.0149],
       grad_fn=<ViewBackward0>)
6
tensor([ 0.0000, 17.1665], grad_fn=<ReluBackward0>)
tensor([6.0217, 6.0217, 6.0217, 6.0217, 6.0217, 6.0217, 6.0217, 6.0218],
       grad_f

# 디코드

In [25]:
model.decoder(torch.tensor([0, 0], dtype=torch.float))

tensor([0.2223, 0.2650, 0.4488, 0.0590, 0.1220, 0.0874, 0.4009, 0.0870],
       grad_fn=<ViewBackward0>)

In [26]:
model.decoder(torch.tensor([0, 2.5], dtype=torch.float))

tensor([1.0501, 1.0501, 1.0501, 1.0501, 1.0501, 1.0501, 1.0501, 1.0501],
       grad_fn=<ViewBackward0>)

In [29]:
model.decoder(torch.tensor([0, 1.5], dtype=torch.float))

tensor([0.7111, 0.7111, 0.7111, 0.7111, 0.7111, 0.7111, 0.7111, 0.7111],
       grad_fn=<ViewBackward0>)

In [30]:
model.decoder(torch.tensor([0, 4.5], dtype=torch.float))

tensor([1.7280, 1.7280, 1.7280, 1.7280, 1.7280, 1.7280, 1.7280, 1.7280],
       grad_fn=<ViewBackward0>)